name: adpative_dashboard_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.1.0
  flutter_gen_runner: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/utils/app_images/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

